# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
repo_url: 'https://github.com/pam-d/about-phlpost'
edit_on_github: false
github_docs_folder: true
sticky_navigation: false
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
